name: navigation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.4=py310h3e5f7c9_0
  - ncurses=6.4=h6a678d5_0
  - openmpi=4.0.4=hdf1f1ad_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.27.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - albumentations==1.4.3
      - aliyun-python-sdk-core==2.15.2
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - av==14.2.0
      - babel==2.16.0
      - basicsr==1.4.2
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.44.1
      - black==21.4b2
      - bleach==6.1.0
      - blessed==1.20.0
      - blinker==1.8.2
      - boto3==1.35.34
      - botocore==1.35.34
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - chumpy==0.70
      - cityscapesscripts==2.2.2
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.0.0
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - controlnet-aux==0.0.7
      - crcmod==1.7
      - cryptography==43.0.1
      - cycler==0.12.1
      - cython==3.0.2
      - dataclasses==0.6
      - dataclasses-json==0.5.14
      - datasets==3.6.0
      - debugpy==1.8.6
      - decorator==5.1.1
      - deepspeed==0.10.3
      - defusedxml==0.7.1
      - detectron2==0.6
      - diffdist==0.1
      - diffusers==0.14.0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.7.0
      - einops-exts==0.0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fairscale==0.4.4
      - fastapi==0.115.0
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - filelock==3.14.0
      - filterpy==1.4.5
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.1.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpustat==1.1.1
      - gradio==3.42.0
      - gradio-client==0.5.0
      - greenlet==3.1.1
      - groundingdino==0.1.0
      - grpcio==1.66.2
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.29.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - infinibatch==0.1.1
      - inflect==7.4.0
      - invisible-watermark==0.2.0
      - iopath==0.1.9
      - ipykernel==6.29.5
      - ipython==8.28.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - kornia==0.6.8
      - kornia-rs==0.1.5
      - langchain==0.0.101
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - linkify-it-py==2.0.3
      - lit==15.0.7
      - litellm==1.48.16
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - lvis==0.5.3
      - markdown==3.7
      - markdown-it-py==2.2.0
      - markdown2==2.5.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmpose==0.28.0
      - model-index==0.1.11
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - mss==9.0.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multiscaledeformableattention==1.0
      - munkres==1.1.4
      - mup==1.0.0
      - mypy-extensions==1.0.0
      - narwhals==1.9.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.23.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - open-clip-torch==2.26.1
      - openai==1.51.0
      - openai-whisper==20240930
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.1
      - ordered-set==4.1.0
      - orjson==3.10.7
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - panopticapi==0.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pathtools==0.1.2
      - peft==0.13.0
      - pexpect==4.9.0
      - pillow==9.4.0
      - platformdirs==4.3.6
      - plyfile==1.1
      - portalocker==2.10.1
      - prettytable==3.11.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==4.25.5
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==1.10.18
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pydot==3.0.2
      - pydub==0.25.1
      - pyglet==1.5.27
      - pygments==2.18.0
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.12
      - pytz==2023.4
      - pywavelets==1.7.0
      - pyyaml==6.0.1
      - pyzmq==26.2.0
      - qwen-vl-utils==0.0.10
      - referencing==0.35.1
      - regex==2023.10.3
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.20.0
      - ruff==0.6.8
      - s3transfer==0.10.2
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - seem==1.0
      - segment-anything==1.0
      - semantic-sam==1.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==3.4.1
      - sentencepiece==0.1.99
      - sentry-sdk==2.16.0
      - setproctitle==1.3.3
      - setuptools==75.1.0
      - shapely==1.8.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - smplx==0.1.28
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==1.4.54
      - stack-data==0.6.3
      - starlette==0.38.6
      - streamlit==1.39.0
      - supervision==0.21.0
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tb-nightly==2.19.0a20241006
      - tenacity==8.5.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - test-tube==0.7.5
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tiktoken==0.8.0
      - timm==1.0.13
      - tinycss2==1.3.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.0.2
      - tomlkit==0.12.0
      - torch==2.4.1+cu124
      - torchaudio==2.4.1+cu124
      - torchgeometry==0.1.2
      - torchmetrics==1.4.2
      - torchvision==0.19.1+cu124
      - tornado==6.4.1
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transformers==4.49.0
      - trimesh==4.4.9
      - triton==3.0.0
      - typeguard==4.3.0
      - typer==0.12.5
      - types-python-dateutil==2.9.0.20241003
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==1.26.20
      - uvicorn==0.31.0
      - vision-datasets==0.2.2
      - wandb==0.15.12
      - watchdog==5.0.3
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webdataset==0.2.100
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xtcocotools==1.14.3
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.13.1
      - zipp==3.20.2
